vim.cmd([[nnoremap <leader>j <Cmd>call VSCodeNotify('workbench.action.quickOpen')<CR>]])
vim.cmd([[nnoremap <C-o> <Cmd>call VSCodeNotify('workbench.action.navigateBack')<CR>]])
vim.cmd([[nnoremap <C-i> <Cmd>call VSCodeNotify('workbench.action.navigateForward')<CR>]])
vim.cmd([[nnoremap <leader>f <Cmd>call VSCodeNotify('workbench.action.findInFiles')<CR>]])
vim.cmd([[nnoremap <leader>\ <Cmd>call VSCodeNotify('workbench.view.explorer')<CR>]])
vim.cmd([[nnoremap gi <Cmd>call VSCodeNotify('editor.action.goToImplementation')<CR>]])
vim.cmd([[nnoremap gI <Cmd>call VSCodeNotify('editor.action.peekImplementation')<CR>]])
