-- require("gitsigns").setup({
-- 	signs = {
-- 		add = {
-- 			hl = "GitSignsAdd",
-- 			numhl = "GitSignsAddNr",
-- 			linehl = "GitSignsAddLn",
-- 		},
-- 		change = {
-- 			hl = "GitSignsChange",
-- 			numhl = "GitSignsChangeNr",
-- 			linehl = "GitSignsChangeLn",
-- 		},
-- 		delete = {
-- 			hl = "GitSignsDelete",
-- 			numhl = "GitSignsDeleteNr",
-- 			linehl = "GitSignsDeleteLn",
-- 		},
-- 		topdelete = {
-- 			hl = "GitSignsDelete",
-- 			numhl = "GitSignsDeleteNr",
-- 			linehl = "GitSignsDeleteLn",
-- 		},
-- 		changedelete = {
-- 			hl = "GitSignsChange",
-- 			numhl = "GitSignsChangeNr",
-- 			linehl = "GitSignsChangeLn",
-- 		},
-- 	},
-- 	signcolumn = true, -- Toggle with `:Gitsigns toggle_signs`
-- 	numhl = false, -- Toggle with `:Gitsigns toggle_numhl`
-- 	linehl = false, -- Toggle with `:Gitsigns toggle_linehl`
-- 	word_diff = false, -- Toggle with `:Gitsigns toggle_word_diff`
-- 	watch_gitdir = { interval = 1000, follow_files = true },
-- 	attach_to_untracked = true,
-- 	current_line_blame = false, -- Toggle with `:Gitsigns toggle_current_line_blame`
-- 	current_line_blame_opts = {
-- 		virt_text = true,
-- 		virt_text_pos = "eol", -- 'eol' | 'overlay' | 'right_align'
-- 		delay = 1000,
-- 		ignore_whitespace = false,
-- 	},
-- 	on_attach = function(bufnr)
-- 		local gs = package.loaded.gitsigns
-- 		local function map(mode, l, r, opts)
-- 			opts = opts or {}
-- 			opts.buffer = bufnr
-- 			vim.keymap.set(mode, l, r, opts)
-- 		end
-- 		map("n", "<leader>gb", function()
-- 			gs.blame_line({ full = true })
-- 		end)
-- 		map("n", "<leader>gp", function()
-- 			if vim.wo.diff then
-- 				return "<leader>gp"
-- 			end
-- 			vim.schedule(function()
-- 				gs.prev_hunk()
-- 			end)
-- 			return "<Ignore>"
-- 		end)
-- 		map("n", "<leader>gn", function()
-- 			if vim.wo.diff then
-- 				return "<leader>gn"
-- 			end
-- 			vim.schedule(function()
-- 				gs.next_hunk()
-- 			end)
-- 			return "<Ignore>"
-- 		end)
-- 	end,
-- 	current_line_blame_formatter_opts = { relative_time = false },
-- 	sign_priority = 6,
-- 	update_debounce = 100,
-- 	status_formatter = nil, -- Use default
-- 	max_file_length = 40000,
-- 	preview_config = {
-- 		-- Options passed to nvim_open_win
-- 		border = "single",
-- 		style = "minimal",
-- 		relative = "cursor",
-- 		row = 0,
-- 		col = 1,
-- 	},
-- 	yadm = { enable = false },
-- })
-- vim.keymap.set("n", "<leader>gr", ":Gitsigns reset_hunk<CR>")
-- vim.keymap.set("n", "<leader>gd", ":Gitsigns preview_hunk<CR>")
